# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-themepack-xenlism-wildfire

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        Xenlism Wildfire
Version:        0.2.9
Release:        2
Group:          Qt/Qt
License:        GPLv3
Packager:       fravaccaro <me@fravaccaro.com>
URL:            https://github.com/uithemer/harbour-themepack-xenlism-wildfire
Source0:        %{name}-%{version}.tar.bz2
Source100:      harbour-themepack-xenlism-wildfire.yaml
Requires:       sailfishsilica-qt5 >= 0.10.9, sailfish-version >= 5.0.0, harbour-muoto >= 3.0.0
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Xenlism Wildfire theme pack for Sailfish OS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%preun
if [ "$1" = "0" ]; then
    rm -rf /home/defaultuser/.local/share/%{name}
    rm -rf /home/defaultuser/.themepack/%{name}
fi

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files

%post
mkdir -p /home/defaultuser/.themepack/%{name}
if [ -d "/usr/share/%{name}/jolla" ]; then
        mv /usr/share/%{name}/jolla /home/defaultuser/.themepack/%{name}/
        ln -s /home/defaultuser/.themepack/%{name}/jolla /usr/share/%{name}/
fi
if [ -d "/usr/share/%{name}/native" ]; then
        mv /usr/share/%{name}/native /home/defaultuser/.themepack/%{name}/
        ln -s /home/defaultuser/.themepack/%{name}/native /usr/share/%{name}/
fi
if [ -d "/usr/share/%{name}/apk" ]; then
        mv /usr/share/%{name}/apk /home/defaultuser/.themepack/%{name}/
        ln -s /home/defaultuser/.themepack/%{name}/apk /usr/share/%{name}/
fi
if [ -d "/usr/share/%{name}/overlay" ]; then
        mv /usr/share/%{name}/overlay /home/defaultuser/.themepack/%{name}/
        ln -s /home/defaultuser/.themepack/%{name}/overlay /usr/share/%{name}/
fi
if [ -d "/usr/share/%{name}/dyncal" ]; then
        mv /usr/share/%{name}/dyncal /home/defaultuser/.themepack/%{name}
        ln -s /home/defaultuser/.themepack/%{name}/dyncal /usr/share/%{name}/dyncal
fi
if [ -d "/usr/share/%{name}/dynclock" ]; then
        mv /usr/share/%{name}/dynclock /home/defaultuser/.themepack/%{name}
        ln -s /home/defaultuser/.themepack/%{name}/dynclock /usr/share/%{name}/
fi
