# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-themepack-xenlism-wildfire

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        Xenlism Wildfire
Version:        0.2.9
Release:        3
Group:          Qt/Qt
License:        GPLv3
Packager:       fravaccaro
URL:            https://github.com/uithemer/harbour-themepack-xenlism-wildfire
Source0:        %{name}-%{version}.tar.bz2
Source100:      harbour-themepack-xenlism-wildfire.yaml
Requires:       sailfishsilica-qt5 >= 0.10.9, sailfish-version >= 5.0.0, harbour-muoto >= 3.0.0
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Xenlism Wildfire theme pack for Sailfish OS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%preun
if [ "$1" = "0" ]; then
        rm -rf /home/defaultuser/.local/share/%{name}

        # Undo the relocation done by %post. RPM recorded these paths as real
        # directories, so it must find real directories here to remove them;
        # left as symlinks it would fail on every packaged file underneath.
        themepackdir=/home/defaultuser/.themepack/%{name}
        for dir in jolla native apk overlay dyncal dynclock; do
                shared=/usr/share/%{name}/$dir
                stored=$themepackdir/$dir

                if [ -L "$shared" ]; then
                        rm -f "$shared"
                        if [ -d "$stored" ]; then
                                mv "$stored" "$shared"
                        fi
                fi
        done

        rm -rf "$themepackdir"
fi
:

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files

%post
themepackdir=/home/defaultuser/.themepack/%{name}
mkdir -p "$themepackdir"
for dir in jolla native apk overlay dyncal dynclock; do
        shared=/usr/share/%{name}/$dir
        stored=$themepackdir/$dir

        if [ -L "$shared" ]; then
                # Already relocated by an earlier install; RPM has just written
                # the new payload straight through the symlink.
                if [ "$(readlink "$shared")" = "$stored" ] && [ -d "$stored" ]; then
                        continue
                fi
                rm -f "$shared"
        fi

        if [ -d "$shared" ]; then
                rm -rf "$stored"
                mv "$shared" "$stored"
        fi

        if [ -d "$stored" ]; then
                ln -sfn "$stored" "$shared"
        fi
done
:
